name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-efi-release:
    name: Build EFI Release
    runs-on: macos-latest
    env:
      XCODE_VERSION: 12.4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '5'

      - name: Initialize Variables
        run: |
          GIT_SHA="$(git rev-parse --short HEAD)"
          echo "CUR_TAG=beta-$GIT_SHA" >> "$GITHUB_ENV"
          echo "DEVELOPER_DIR=/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer" >> "$GITHUB_ENV"

      - name: Manage Release Version
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          echo "CUR_TAG=${GITHUB_REF##*/}" >> "$GITHUB_ENV"

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ASUS A455LF-WX039D NoteBook EFI ${{ env.CUR_TAG }}
      #     path: build/*.zip

      - name: Upload to Release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.13.0
        with:
      #     artifacts: build/*.zip
          name: ASUS A455LF-WX039D NoteBook EFI ${{ env.CUR_TAG }}
          prerelease: true
          tag: ${{ env.CUR_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
