name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-efi-pre-release:
    name: Build EFI Pre-release
    runs-on: macos-latest
    env:
      XCODE_VERSION: 12.4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '5'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Initialize Variables
        run: |
          GIT_SHA="$(git rev-parse --short HEAD)"
          echo "CUR_TAG=beta-$GIT_SHA" >> "$GITHUB_ENV"
          echo "DEVELOPER_DIR=/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer" >> "$GITHUB_ENV"

      - name: Manage Pre-release Version
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          echo "CUR_TAG=${GITHUB_REF##*/}" >> "$GITHUB_ENV"

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: EFI ASUS A455LF ${{ env.CUR_TAG }}
          path: Pre-Release/*.zip

      - name: Upload to Pre-release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: Pre-release/*.zip
          name: EFI ASUS A455LF ${{ env.CUR_TAG }}
          prerelease: true
          tag: ${{ env.CUR_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
